package category

import sharedpb "github.com/MamangRust/microservice-ecommerce-shared/pb"

type categoryCommandServiceClient = sharedpb.categoryCommandServiceClient
type categoryQueryServiceClient = sharedpb.categoryQueryServiceClient
type categoryStatsByIdServiceClient = sharedpb.categoryStatsByIdServiceClient
type categoryStatsByMerchantServiceClient = sharedpb.categoryStatsByMerchantServiceClient
type categoryStatsServiceClient = sharedpb.categoryStatsServiceClient
var NewCategoryCommandServiceClient = sharedpb.NewCategoryCommandServiceClient
var NewCategoryQueryServiceClient = sharedpb.NewCategoryQueryServiceClient
var NewCategoryStatsByIdServiceClient = sharedpb.NewCategoryStatsByIdServiceClient
var NewCategoryStatsByMerchantServiceClient = sharedpb.NewCategoryStatsByMerchantServiceClient
var NewCategoryStatsServiceClient = sharedpb.NewCategoryStatsServiceClient
var RegisterCategoryCommandServiceServer = sharedpb.RegisterCategoryCommandServiceServer
var RegisterCategoryQueryServiceServer = sharedpb.RegisterCategoryQueryServiceServer
var RegisterCategoryStatsByIdServiceServer = sharedpb.RegisterCategoryStatsByIdServiceServer
var RegisterCategoryStatsByMerchantServiceServer = sharedpb.RegisterCategoryStatsByMerchantServiceServer
var RegisterCategoryStatsServiceServer = sharedpb.RegisterCategoryStatsServiceServer
