package merchant_policygraphqlmapper

import (
	"github.com/MamangRust/microservice-ecommerce-grpc-apigateway/internal/model"
	"github.com/MamangRust/microservice-ecommerce-grpc-pb/merchant"
	"github.com/MamangRust/microservice-ecommerce-grpc-pb/merchant_policy"
)

type MerchantPolicyGraphqlMapper interface {
	ToGraphqlResponseMerchantPolicyDelete(res *pb_merchant.ApiResponseMerchantDelete) *model.APIResponseMerchantPolicyDelete
	ToGraphqlResponseMerchantPolicyAll(res *pb_merchant.ApiResponseMerchantAll) *model.APIResponseMerchantPolicyAll
	ToGraphqlResponseMerchantPolicy(res *pb_merchant_policy.ApiResponseMerchantPolicies) *model.APIResponseMerchantPolicy
	ToGraphqlResponseMerchantPolicyDeleteAt(res *pb_merchant_policy.ApiResponseMerchantPoliciesDeleteAt) *model.APIResponseMerchantPolicyDeleteAt
	ToGraphqlResponsesMerchantPolicy(res *pb_merchant_policy.ApiResponsesMerchantPolicies) *model.APIResponsesMerchantPolicy
	ToGraphqlResponsePaginationMerchantPolicyDeleteAt(res *pb_merchant_policy.ApiResponsePaginationMerchantPoliciesDeleteAt) *model.APIResponsePaginationMerchantPolicyDeleteAt
	ToGraphqlResponsePaginationMerchantPolicy(res *pb_merchant_policy.ApiResponsePaginationMerchantPolicies) *model.APIResponsePaginationMerchantPolicy
}
