package transaction

import sharedpb "github.com/MamangRust/microservice-ecommerce-shared/pb"

type transactionCommandServiceClient = sharedpb.transactionCommandServiceClient
type transactionQueryServiceClient = sharedpb.transactionQueryServiceClient
type transactionStatsByMerchantServiceClient = sharedpb.transactionStatsByMerchantServiceClient
type transactionStatsServiceClient = sharedpb.transactionStatsServiceClient
var NewTransactionCommandServiceClient = sharedpb.NewTransactionCommandServiceClient
var NewTransactionQueryServiceClient = sharedpb.NewTransactionQueryServiceClient
var NewTransactionStatsByMerchantServiceClient = sharedpb.NewTransactionStatsByMerchantServiceClient
var NewTransactionStatsServiceClient = sharedpb.NewTransactionStatsServiceClient
var RegisterTransactionCommandServiceServer = sharedpb.RegisterTransactionCommandServiceServer
var RegisterTransactionQueryServiceServer = sharedpb.RegisterTransactionQueryServiceServer
var RegisterTransactionStatsByMerchantServiceServer = sharedpb.RegisterTransactionStatsByMerchantServiceServer
var RegisterTransactionStatsServiceServer = sharedpb.RegisterTransactionStatsServiceServer
