package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/MamangRust/microservice-ecommerce-shared/domain/requests"
	sharedErrors "github.com/MamangRust/microservice-ecommerce-shared/errors"
	"github.com/MamangRust/microservice-ecommerce-shared/pb"
	mycontext "github.com/MamangRust/monolith-graphql-ecommerce-apigateway/internal/context"
	graphqlerror "github.com/MamangRust/monolith-graphql-ecommerce-apigateway/internal/errors"
	"github.com/MamangRust/monolith-graphql-ecommerce-apigateway/internal/model"
)

// CreateCart is the resolver for the createCart field.
func (r *mutationResolver) CreateCart(ctx context.Context, input model.CreateCartInput) (*model.APIResponseCart, error) {
	return ResolverHandle(r.ResolverHandle, "CreateCart", ctx, func(ctx context.Context) (*model.APIResponseCart, error) {
		req := &requests.CreateCartRequest{
			Quantity:  int(input.Quantity),
			ProductID: int(input.ProductID),
			UserID:    int(input.UserID),
		}

		if err := req.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewValidationError(validations))
		}

		reqPb := &pb.CreateCartRequest{
			Quantity:  int32(req.Quantity),
			ProductId: int32(req.ProductID),
			UserId:    int32(req.UserID),
		}

		cartItem, err := r.CartGraphql.CartCommandClient.Create(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "CreateCart")
		}

		so := r.CartGraphql.Mapping.ToGraphqlResponseCart(cartItem)

		return so, nil
	})
}

// DeleteCart is the resolver for the deleteCart field.
func (r *mutationResolver) DeleteCart(ctx context.Context, input model.DeleteCartInput) (*model.APIResponseCartDelete, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteCart", ctx, func(ctx context.Context) (*model.APIResponseCartDelete, error) {
		id := int(input.CartID)

		if id <= 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("id is required"))
		}

		reqPb := &pb.DeleteCartRequest{
			CartId: int32(id),
			UserId: int32(input.UserID),
		}

		res, err := r.CartGraphql.CartCommandClient.Delete(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteCart")
		}

		so := r.CartGraphql.Mapping.ToGraphqlResponseCartDelete(res)

		return so, nil
	})
}

// DeleteAllCarts is the resolver for the deleteAllCarts field.
func (r *mutationResolver) DeleteAllCarts(ctx context.Context, input model.DeleteCartsInput) (*model.APIResponseCartAll, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteAllCarts", ctx, func(ctx context.Context) (*model.APIResponseCartAll, error) {
		cartIDs := make([]int32, len(input.CartIds))
		for i, id := range input.CartIds {
			cartIDs[i] = int32(id)
		}

		uid, ok := mycontext.UserForContext(ctx)
		if !ok || uid == 0 {
			return nil, sharedErrors.NewBadRequestError("invalid request: user ID cannot be zero")
		}

		req := &pb.DeleteAllCartRequest{
			UserId:  int32(uid),
			CartIds: cartIDs,
		}

		res, err := r.CartGraphql.CartCommandClient.DeleteAll(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteAllCarts")
		}

		so := r.CartGraphql.Mapping.ToGraphqlResponseCartAll(res)

		return so, nil
	})
}

// FindAllCarts is the resolver for the findAllCarts field.
func (r *queryResolver) FindAllCarts(ctx context.Context, input model.FindAllCartInput) (*model.APIResponsePaginationCart, error) {
	return ResolverHandle(r.ResolverHandle, "FindAllCarts", ctx, func(ctx context.Context) (*model.APIResponsePaginationCart, error) {
		userID := input.UserID
		page := int32(1)
		pageSize := int32(10)
		search := ""

		if input.Page != nil {
			page = int32(*input.Page)
		}
		if input.PageSize != nil {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}

		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		normalizedInput := &model.FindAllCartInput{
			Page:     &page,
			PageSize: &pageSize,
			UserID:   userID,
			Search:   &search,
		}

		if cached, found := r.CartGraphql.Cache.GetCachedCarts(ctx, normalizedInput); found {
			return cached, nil
		}

		req := &pb.FindAllCartRequest{
			UserId:   userID,
			Page:     page,
			PageSize: pageSize,
			Search:   search,
		}

		cartItems, err := r.CartGraphql.CartQueryClient.FindAll(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindAllCarts")
		}

		so := r.CartGraphql.Mapping.ToGraphqlResponsePaginationCart(cartItems)

		r.CartGraphql.Cache.SetCachedCarts(ctx, normalizedInput, so)

		return so, nil
	})
}
