package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"time"

	graphqlerror "github.com/MamangRust/microservice-ecommerce-grpc-apigateway/internal/errors"
	"github.com/MamangRust/microservice-ecommerce-grpc-apigateway/internal/model"
	"github.com/MamangRust/microservice-ecommerce-grpc-pb/category"
	"github.com/MamangRust/microservice-ecommerce-shared/domain/requests"
	sharedErrors "github.com/MamangRust/microservice-ecommerce-shared/errors"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.CreateCategoryInput) (*model.APIResponseCategory, error) {
	return ResolverHandle(r.ResolverHandle, "CreateCategory", ctx, func(ctx context.Context) (*model.APIResponseCategory, error) {
		var imagePath string

		if input.ImageCategory.Filename != "" && input.ImageCategory.ContentType != "" {

			upload := input.ImageCategory.File
			ext := filepath.Ext(input.ImageCategory.Filename)
			filename := fmt.Sprintf("%d%s", time.Now().UnixNano(), ext)
			imagePath = filepath.Join("uploads/category", filename)

			if err := r.CategoryGraphql.UploadImage.EnsureUploadDirectory("uploads/category"); err != nil {
				return nil, r.handleGraphQLError(err, "CreateCategory")
			}

			out, err := os.Create(imagePath)
			if err != nil {
				return nil, r.handleGraphQLError(err, "CreateCategory")
			}
			defer out.Close()

			if _, err := io.Copy(out, upload); err != nil {
				r.CategoryGraphql.UploadImage.CleanupImageOnFailure(imagePath)
				return nil, r.handleGraphQLError(err, "CreateCategory")
			}
		}

		req := &requests.CreateCategoryRequest{
			Name:          input.Name,
			Description:   input.Description,
			SlugCategory:  &input.SlugCategory,
			ImageCategory: imagePath,
		}

		if err := req.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewValidationError(validations))
		}

		reqPb := &pb_category.CreateCategoryRequest{
			Name:          req.Name,
			Description:   req.Description,
			ImageCategory: req.ImageCategory,
		}

		res, err := r.CategoryGraphql.CategoryCommandClient.Create(ctx, reqPb)

		if err != nil {
			return nil, r.handleGraphQLError(err, "CreateCategory")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategory(res)

		r.CategoryGraphql.Cache.DeleteCachedCategoryCache(ctx, int(so.Data.ID))

		return so, nil
	})
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, input model.UpdateCategoryInput) (*model.APIResponseCategory, error) {
	return ResolverHandle(r.ResolverHandle, "UpdateCategory", ctx, func(ctx context.Context) (*model.APIResponseCategory, error) {
		id := int(input.CategoryID)

		if id <= 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("id is required"))
		}

		var imagePath string

		if input.ImageCategory.Filename != "" && input.ImageCategory.ContentType != "" {

			upload := input.ImageCategory.File
			ext := filepath.Ext(input.ImageCategory.Filename)
			filename := fmt.Sprintf("%d%s", time.Now().UnixNano(), ext)
			imagePath = filepath.Join("uploads/category", filename)

			if err := r.CategoryGraphql.UploadImage.EnsureUploadDirectory("uploads/category"); err != nil {
				return nil, r.handleGraphQLError(err, "UpdateCategory")
			}

			out, err := os.Create(imagePath)
			if err != nil {
				return nil, r.handleGraphQLError(err, "UpdateCategory")
			}
			defer out.Close()

			if _, err := io.Copy(out, upload); err != nil {
				r.CategoryGraphql.UploadImage.CleanupImageOnFailure(imagePath)
				return nil, r.handleGraphQLError(err, "UpdateCategory")
			}
		}

		req := &requests.UpdateCategoryRequest{
			CategoryID:    &id,
			Name:          input.Name,
			Description:   input.Description,
			SlugCategory:  &input.SlugCategory,
			ImageCategory: imagePath,
		}

		if err := req.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewValidationError(validations))
		}

		reqPb := &pb_category.UpdateCategoryRequest{
			CategoryId:    int32(id),
			Name:          req.Name,
			Description:   req.Description,
			ImageCategory: req.ImageCategory,
		}

		res, err := r.CategoryGraphql.CategoryCommandClient.Update(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "UpdateCategory")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategory(res)

		r.CategoryGraphql.Cache.DeleteCachedCategoryCache(ctx, id)

		return so, nil
	})
}

// TrashCategory is the resolver for the trashCategory field.
func (r *mutationResolver) TrashCategory(ctx context.Context, input model.FindByIDCategoryInput) (*model.APIResponseCategoryDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "TrashCategory", ctx, func(ctx context.Context) (*model.APIResponseCategoryDeleteAt, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("id is required"))
		}

		reqPb := &pb_category.FindByIdCategoryRequest{
			Id: int32(id),
		}

		category, err := r.CategoryGraphql.CategoryCommandClient.TrashedCategory(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "TrashCategory")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryDeleteAt(category)

		r.CategoryGraphql.Cache.DeleteCachedCategoryCache(ctx, id)

		return so, nil
	})
}

// RestoreCategory is the resolver for the restoreCategory field.
func (r *mutationResolver) RestoreCategory(ctx context.Context, input model.FindByIDCategoryInput) (*model.APIResponseCategoryDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreCategory", ctx, func(ctx context.Context) (*model.APIResponseCategoryDeleteAt, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("id is required"))
		}

		reqPb := &pb_category.FindByIdCategoryRequest{
			Id: int32(id),
		}

		category, err := r.CategoryGraphql.CategoryCommandClient.RestoreCategory(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreCategory")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryDeleteAt(category)

		r.CategoryGraphql.Cache.DeleteCachedCategoryCache(ctx, id)

		return so, nil
	})
}

// DeleteCategoryPermanent is the resolver for the deleteCategoryPermanent field.
func (r *mutationResolver) DeleteCategoryPermanent(ctx context.Context, input model.FindByIDCategoryInput) (*model.APIResponseCategoryDelete, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteCategoryPermanent", ctx, func(ctx context.Context) (*model.APIResponseCategoryDelete, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("id is required"))
		}

		reqPb := &pb_category.FindByIdCategoryRequest{
			Id: int32(id),
		}

		res, err := r.CategoryGraphql.CategoryCommandClient.DeleteCategoryPermanent(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteCategoryPermanent")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryDelete(res)

		r.CategoryGraphql.Cache.DeleteCachedCategoryCache(ctx, id)

		return so, nil
	})
}

// RestoreAllCategories is the resolver for the restoreAllCategories field.
func (r *mutationResolver) RestoreAllCategories(ctx context.Context) (*model.APIResponseCategoryAll, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreAllCategories", ctx, func(ctx context.Context) (*model.APIResponseCategoryAll, error) {
		res, err := r.CategoryGraphql.CategoryCommandClient.RestoreAllCategory(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreAllCategories")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryAll(res)

		return so, nil
	})
}

// DeleteAllCategoriesPermanent is the resolver for the deleteAllCategoriesPermanent field.
func (r *mutationResolver) DeleteAllCategoriesPermanent(ctx context.Context) (*model.APIResponseCategoryAll, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteAllCategoriesPermanent", ctx, func(ctx context.Context) (*model.APIResponseCategoryAll, error) {
		res, err := r.CategoryGraphql.CategoryCommandClient.DeleteAllCategoryPermanent(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteAllCategoriesPermanent")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategoryAll(res)

		return so, nil
	})
}

// FindAllCategories is the resolver for the findAllCategories field.
func (r *queryResolver) FindAllCategories(ctx context.Context, input model.FindAllCategoryInput) (*model.APIResponsePaginationCategory, error) {
	return ResolverHandle(r.ResolverHandle, "FindAllCategories", ctx, func(ctx context.Context) (*model.APIResponsePaginationCategory, error) {
		// Prepare Input Defaults
		page := int32(1)
		pageSize := int32(10)
		search := ""

		if input.Page != nil {
			page = int32(*input.Page)
		}
		if input.PageSize != nil {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}

		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		// Prepare Cache Key
		cacheReq := &model.FindAllCategoryInput{
			Page:     input.Page,
			PageSize: input.PageSize,
			Search:   input.Search,
		}

		if data, found := r.CategoryGraphql.Cache.GetCachedCategoriesCache(ctx, cacheReq); found {
			return data, nil
		}

		req := &pb_category.FindAllCategoryRequest{
			Page:     page,
			PageSize: pageSize,
			Search:   search,
		}

		categories, err := r.CategoryGraphql.CategoryQueryClient.FindAll(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindAllCategories")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponsePaginationCategory(categories)

		r.CategoryGraphql.Cache.SetCachedCategoriesCache(ctx, cacheReq, so)

		return so, nil
	})
}

// FindCategoryByID is the resolver for the findCategoryById field.
func (r *queryResolver) FindCategoryByID(ctx context.Context, input model.FindByIDCategoryInput) (*model.APIResponseCategory, error) {
	return ResolverHandle(r.ResolverHandle, "FindCategoryByID", ctx, func(ctx context.Context) (*model.APIResponseCategory, error) {
		id := int(input.ID)
		if id == 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: category ID cannot be zero"))
		}

		if data, found := r.CategoryGraphql.Cache.GetCachedCategoryCache(ctx, id); found {
			return data, nil
		}

		category, err := r.CategoryGraphql.CategoryQueryClient.FindById(ctx, &pb_category.FindByIdCategoryRequest{
			Id: int32(id),
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindCategoryByID")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponseCategory(category)

		r.CategoryGraphql.Cache.SetCachedCategoryCache(ctx, so)

		return so, nil
	})
}

// FindActiveCategories is the resolver for the findActiveCategories field.
func (r *queryResolver) FindActiveCategories(ctx context.Context, input model.FindAllCategoryInput) (*model.APIResponsePaginationCategoryDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindActiveCategories", ctx, func(ctx context.Context) (*model.APIResponsePaginationCategoryDeleteAt, error) {
		// Prepare Input Defaults
		page := int32(1)
		pageSize := int32(10)
		search := ""

		if input.Page != nil {
			page = int32(*input.Page)
		}
		if input.PageSize != nil {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}

		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		// Prepare Cache Key
		cacheReq := &model.FindAllCategoryInput{
			Page:     input.Page,
			PageSize: input.PageSize,
			Search:   input.Search,
		}

		if data, found := r.CategoryGraphql.Cache.GetCachedCategoryActiveCache(ctx, cacheReq); found {
			return data, nil
		}

		req := &pb_category.FindAllCategoryRequest{
			Page:     page,
			PageSize: pageSize,
			Search:   search,
		}

		categories, err := r.CategoryGraphql.CategoryQueryClient.FindByActive(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindActiveCategories")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponsePaginationCategoryDeleteAt(categories)

		r.CategoryGraphql.Cache.SetCachedCategoryActiveCache(ctx, cacheReq, so)

		return so, nil
	})
}

// FindTrashedCategories is the resolver for the findTrashedCategories field.
func (r *queryResolver) FindTrashedCategories(ctx context.Context, input model.FindAllCategoryInput) (*model.APIResponsePaginationCategoryDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindTrashedCategories", ctx, func(ctx context.Context) (*model.APIResponsePaginationCategoryDeleteAt, error) {
		// Prepare Input Defaults
		page := int32(1)
		pageSize := int32(10)
		search := ""

		if input.Page != nil {
			page = int32(*input.Page)
		}
		if input.PageSize != nil {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}

		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		// Prepare Cache Key
		cacheReq := &model.FindAllCategoryInput{
			Page:     input.Page,
			PageSize: input.PageSize,
			Search:   input.Search,
		}

		if data, found := r.CategoryGraphql.Cache.GetCachedCategoryTrashedCache(ctx, cacheReq); found {
			return data, nil
		}

		req := &pb_category.FindAllCategoryRequest{
			Page:     page,
			PageSize: pageSize,
			Search:   search,
		}

		categories, err := r.CategoryGraphql.CategoryQueryClient.FindByTrashed(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindTrashedCategories")
		}

		so := r.CategoryGraphql.Mapping.ToGraphqlResponsePaginationCategoryDeleteAt(categories)

		r.CategoryGraphql.Cache.SetCachedCategoryTrashedCache(ctx, cacheReq, so)

		return so, nil
	})
}

// Stats resolvers moved to stats.resolvers.go
