package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	graphqlerror "github.com/MamangRust/microservice-ecommerce-grpc-apigateway/internal/errors"
	"github.com/MamangRust/microservice-ecommerce-grpc-apigateway/internal/model"
	"github.com/MamangRust/microservice-ecommerce-grpc-pb/merchant_social_link"
	sharedErrors "github.com/MamangRust/microservice-ecommerce-shared/errors"
)

// CreateMerchantSocialLink is the resolver for the createMerchantSocialLink field.
func (r *mutationResolver) CreateMerchantSocialLink(ctx context.Context, input *model.CreateMerchantSocialInput) (*model.APIResponseMerchantSocialMediaLink, error) {
	return ResolverHandle(r.ResolverHandle, "CreateMerchantSocialLink", ctx, func(ctx context.Context) (*model.APIResponseMerchantSocialMediaLink, error) {
		if input == nil || input.MerchantDetailID == 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: merchant detail ID cannot be zero"))
		}

		req := &pb_merchant_social_link.CreateMerchantSocialRequest{
			MerchantDetailId: int32(input.MerchantDetailID),
			Platform:         input.Platform,
			Url:              input.URL,
		}

		res, err := r.MerchantSocialLinkGraphql.MerchantSocialLinkClient.Create(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "CreateMerchantSocialLink")
		}

		return r.MerchantSocialLinkGraphql.Mapping.ToGraphqlResponseMerchantSocialLink(res), nil
	})
}

// UpdateMerchantSocialLink is the resolver for the updateMerchantSocialLink field.
func (r *mutationResolver) UpdateMerchantSocialLink(ctx context.Context, input *model.UpdateMerchantSocialInput) (*model.APIResponseMerchantSocialMediaLink, error) {
	return ResolverHandle(r.ResolverHandle, "UpdateMerchantSocialLink", ctx, func(ctx context.Context) (*model.APIResponseMerchantSocialMediaLink, error) {
		if input == nil || input.ID == 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: social link ID cannot be zero"))
		}

		req := &pb_merchant_social_link.UpdateMerchantSocialRequest{
			Id:               int32(input.ID),
			MerchantDetailId: int32(input.MerchantDetailID),
			Platform:         input.Platform,
			Url:              input.URL,
		}

		res, err := r.MerchantSocialLinkGraphql.MerchantSocialLinkClient.Update(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "UpdateMerchantSocialLink")
		}

		return r.MerchantSocialLinkGraphql.Mapping.ToGraphqlResponseMerchantSocialLink(res), nil
	})
}
