package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	graphqlerror "github.com/MamangRust/microservice-ecommerce-grpc-apigateway/internal/errors"
	"github.com/MamangRust/microservice-ecommerce-grpc-apigateway/internal/model"
	"github.com/MamangRust/microservice-ecommerce-grpc-pb/order"
	"github.com/MamangRust/microservice-ecommerce-grpc-pb/shipping_address"
	sharedErrors "github.com/MamangRust/microservice-ecommerce-shared/errors"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput) (*model.APIResponseOrder, error) {
	return ResolverHandle(r.ResolverHandle, "CreateOrder", ctx, func(ctx context.Context) (*model.APIResponseOrder, error) {
		if input.MerchantID == 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: merchant ID cannot be zero"))
		}
		if input.UserID == 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: user ID cannot be zero"))
		}

		req := &pb_order.CreateOrderRequest{
			MerchantId: int32(input.MerchantID),
			UserId:     int32(input.UserID),
			TotalPrice: int32(input.TotalPrice),
		}

		for _, item := range input.Items {
			req.Items = append(req.Items, &pb_order.CreateOrderItemRequest{
				ProductId: int32(item.ProductID),
				Quantity:  int32(item.Quantity),
				Price:     int32(item.Price),
			})
		}

		if input.Shipping != nil {
			req.Shipping = &pb_shipping_address.CreateShippingAddressRequest{
				Alamat:         input.Shipping.Alamat,
				Provinsi:       input.Shipping.Provinsi,
				Kota:           input.Shipping.Kota,
				Courier:        input.Shipping.Courier,
				ShippingMethod: input.Shipping.ShippingMethod,
				ShippingCost:   int32(input.Shipping.ShippingCost),
				Negara:         input.Shipping.Negara,
			}
		}

		order, err := r.OrderGraphql.OrderCommandClient.Create(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "CreateOrder")
		}

		res := r.OrderGraphql.Mapping.ToGraphqlResponseOrder(order)

		r.OrderGraphql.Cache.DeleteOrderCache(ctx, int(res.Data.ID))

		return res, nil
	})
}

// UpdateOrder is the resolver for the updateOrder field.
func (r *mutationResolver) UpdateOrder(ctx context.Context, input model.UpdateOrderInput) (*model.APIResponseOrder, error) {
	return ResolverHandle(r.ResolverHandle, "UpdateOrder", ctx, func(ctx context.Context) (*model.APIResponseOrder, error) {
		id := int32(input.OrderID)
		idShipping := 0
		if input.Shipping != nil {
			idShipping = int(input.Shipping.ShippingID)
		}

		if id == 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: order ID cannot be zero"))
		}

		req := &pb_order.UpdateOrderRequest{
			OrderId:    id,
			UserId:     int32(input.UserID),
			TotalPrice: int32(input.TotalPrice),
		}

		for _, item := range input.Items {
			req.Items = append(req.Items, &pb_order.UpdateOrderItemRequest{
				OrderItemId: int32(item.OrderItemID),
				ProductId:   int32(item.ProductID),
				Quantity:    int32(item.Quantity),
				Price:       int32(item.Price),
			})
		}

		if input.Shipping != nil {
			req.Shipping = &pb_shipping_address.UpdateShippingAddressRequest{
				ShippingId:     int32(idShipping),
				Alamat:         *input.Shipping.Alamat,
				Provinsi:       *input.Shipping.Provinsi,
				Kota:           *input.Shipping.Kota,
				Courier:        *input.Shipping.Courier,
				ShippingMethod: *input.Shipping.ShippingMethod,
				ShippingCost:   int32(*input.Shipping.ShippingCost),
				Negara:         *input.Shipping.Negara,
			}
		}

		order, err := r.OrderGraphql.OrderCommandClient.Update(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "UpdateOrder")
		}

		res := r.OrderGraphql.Mapping.ToGraphqlResponseOrder(order)

		r.OrderGraphql.Cache.DeleteOrderCache(ctx, int(id))

		return res, nil
	})
}

// TrashOrder is the resolver for the trashOrder field.
func (r *mutationResolver) TrashOrder(ctx context.Context, input model.FindByIDOrderInput) (*model.APIResponseOrderDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "TrashOrder", ctx, func(ctx context.Context) (*model.APIResponseOrderDeleteAt, error) {
		id := int32(input.ID)
		if id == 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: order ID cannot be zero"))
		}

		order, err := r.OrderGraphql.OrderCommandClient.TrashedOrder(ctx, &pb_order.FindByIdOrderRequest{
			Id: id,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "TrashOrder")
		}

		res := r.OrderGraphql.Mapping.ToGraphqlResponseOrderDeleteAt(order)

		r.OrderGraphql.Cache.DeleteOrderCache(ctx, int(id))

		return res, nil
	})
}

// RestoreOrder is the resolver for the restoreOrder field.
func (r *mutationResolver) RestoreOrder(ctx context.Context, input model.FindByIDOrderInput) (*model.APIResponseOrderDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreOrder", ctx, func(ctx context.Context) (*model.APIResponseOrderDeleteAt, error) {
		id := int32(input.ID)
		if id == 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: order ID cannot be zero"))
		}

		order, err := r.OrderGraphql.OrderCommandClient.RestoreOrder(ctx, &pb_order.FindByIdOrderRequest{
			Id: id,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreOrder")
		}

		res := r.OrderGraphql.Mapping.ToGraphqlResponseOrderDeleteAt(order)

		r.OrderGraphql.Cache.DeleteOrderCache(ctx, int(id))

		return res, nil
	})
}

// DeleteOrderPermanent is the resolver for the deleteOrderPermanent field.
func (r *mutationResolver) DeleteOrderPermanent(ctx context.Context, input model.FindByIDOrderInput) (*model.APIResponseOrderDelete, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteOrderPermanent", ctx, func(ctx context.Context) (*model.APIResponseOrderDelete, error) {
		id := int32(input.ID)
		if id == 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: order ID cannot be zero"))
		}

		res, err := r.OrderGraphql.OrderCommandClient.DeleteOrderPermanent(ctx, &pb_order.FindByIdOrderRequest{
			Id: id,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteOrderPermanent")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseOrderDelete(res)

		r.OrderGraphql.Cache.DeleteOrderCache(ctx, int(id))

		return so, nil
	})
}

// RestoreAllOrders is the resolver for the restoreAllOrders field.
func (r *mutationResolver) RestoreAllOrders(ctx context.Context) (*model.APIResponseOrderAll, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreAllOrders", ctx, func(ctx context.Context) (*model.APIResponseOrderAll, error) {
		res, err := r.OrderGraphql.OrderCommandClient.RestoreAllOrder(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreAllOrders")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseOrderAll(res)

		return so, nil
	})
}

// DeleteAllOrdersPermanent is the resolver for the deleteAllOrdersPermanent field.
func (r *mutationResolver) DeleteAllOrdersPermanent(ctx context.Context) (*model.APIResponseOrderAll, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteAllOrdersPermanent", ctx, func(ctx context.Context) (*model.APIResponseOrderAll, error) {
		res, err := r.OrderGraphql.OrderCommandClient.DeleteAllOrderPermanent(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteAllOrdersPermanent")
		}

		so := r.OrderGraphql.Mapping.ToGraphqlResponseOrderAll(res)

		return so, nil
	})
}

// FindAllOrders is the resolver for the findAllOrders field.
func (r *queryResolver) FindAllOrders(ctx context.Context, input model.FindAllOrderInput) (*model.APIResponsePaginationOrder, error) {
	return ResolverHandle(r.ResolverHandle, "FindAllOrders", ctx, func(ctx context.Context) (*model.APIResponsePaginationOrder, error) {
		// Prepare Input Defaults
		page := int32(1)
		pageSize := int32(10)
		search := ""

		if input.Page != nil {
			page = int32(*input.Page)
		}
		if input.PageSize != nil {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}

		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		// Note: Assuming input type is compatible with cache interface key
		if data, found := r.OrderGraphql.Cache.GetOrderAllCache(ctx, &input); found {
			return data, nil
		}

		req := &pb_order.FindAllOrderRequest{
			Page:     page,
			PageSize: pageSize,
			Search:   search,
		}

		orders, err := r.OrderGraphql.OrderQueryClient.FindAll(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindAllOrders")
		}

		res := r.OrderGraphql.Mapping.ToGraphqlResponsePaginationOrder(orders)

		r.OrderGraphql.Cache.SetOrderAllCache(ctx, &input, res)

		return res, nil
	})
}

// FindOrderByID is the resolver for the findOrderById field.
func (r *queryResolver) FindOrderByID(ctx context.Context, input model.FindByIDOrderInput) (*model.APIResponseOrder, error) {
	return ResolverHandle(r.ResolverHandle, "FindOrderByID", ctx, func(ctx context.Context) (*model.APIResponseOrder, error) {
		id := int(input.ID)
		if id == 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: order ID cannot be zero"))
		}

		if data, found := r.OrderGraphql.Cache.GetCachedOrderCache(ctx, id); found {
			return data, nil
		}

		order, err := r.OrderGraphql.OrderQueryClient.FindById(ctx, &pb_order.FindByIdOrderRequest{
			Id: int32(id),
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindOrderByID")
		}

		res := r.OrderGraphql.Mapping.ToGraphqlResponseOrder(order)

		r.OrderGraphql.Cache.SetCachedOrderCache(ctx, res)

		return res, nil
	})
}

// FindActiveOrders is the resolver for the findActiveOrders field.
func (r *queryResolver) FindActiveOrders(ctx context.Context, input model.FindAllOrderInput) (*model.APIResponsePaginationOrderDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindActiveOrders", ctx, func(ctx context.Context) (*model.APIResponsePaginationOrderDeleteAt, error) {
		// Prepare Input Defaults
		page := int32(1)
		pageSize := int32(10)
		search := ""

		if input.Page != nil {
			page = int32(*input.Page)
		}
		if input.PageSize != nil {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}

		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		if data, found := r.OrderGraphql.Cache.GetOrderActiveCache(ctx, &input); found {
			return data, nil
		}

		req := &pb_order.FindAllOrderRequest{
			Page:     page,
			PageSize: pageSize,
			Search:   search,
		}

		orders, err := r.OrderGraphql.OrderQueryClient.FindByActive(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindActiveOrders")
		}

		res := r.OrderGraphql.Mapping.ToGraphqlResponsePaginationOrderDeleteAt(orders)

		r.OrderGraphql.Cache.SetOrderActiveCache(ctx, &input, res)

		return res, nil
	})
}

// FindTrashedOrders is the resolver for the findTrashedOrders field.
func (r *queryResolver) FindTrashedOrders(ctx context.Context, input model.FindAllOrderInput) (*model.APIResponsePaginationOrderDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindTrashedOrders", ctx, func(ctx context.Context) (*model.APIResponsePaginationOrderDeleteAt, error) {
		// Prepare Input Defaults
		page := int32(1)
		pageSize := int32(10)
		search := ""

		if input.Page != nil {
			page = int32(*input.Page)
		}
		if input.PageSize != nil {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}

		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		if data, found := r.OrderGraphql.Cache.GetOrderTrashedCache(ctx, &input); found {
			return data, nil
		}

		req := &pb_order.FindAllOrderRequest{
			Page:     page,
			PageSize: pageSize,
			Search:   search,
		}

		orders, err := r.OrderGraphql.OrderQueryClient.FindByTrashed(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindTrashedOrders")
		}

		res := r.OrderGraphql.Mapping.ToGraphqlResponsePaginationOrderDeleteAt(orders)

		r.OrderGraphql.Cache.SetOrderTrashedCache(ctx, &input, res)

		return res, nil
	})
}
