package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	mycontext "github.com/MamangRust/microservice-ecommerce-grpc-apigateway/internal/context"
	graphqlerror "github.com/MamangRust/microservice-ecommerce-grpc-apigateway/internal/errors"
	"github.com/MamangRust/microservice-ecommerce-grpc-apigateway/internal/model"
	"github.com/MamangRust/microservice-ecommerce-grpc-pb/transaction"
	sharedErrors "github.com/MamangRust/microservice-ecommerce-shared/errors"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateTransaction is the resolver for the createTransaction field.
func (r *mutationResolver) CreateTransaction(ctx context.Context, input model.CreateTransactionRequest) (*model.APIResponseTransaction, error) {
	return ResolverHandle(r.ResolverHandle, "CreateTransaction", ctx, func(ctx context.Context) (*model.APIResponseTransaction, error) {
		if input.OrderID == 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: order ID cannot be zero"))
		}

		// The schema does not expose user_id; the transaction belongs to the
		// authenticated caller, populated by AuthMiddleware into the context.
		uid, _ := mycontext.UserForContext(ctx)

		req := &pb_transaction.CreateTransactionRequest{
			OrderId:       int32(input.OrderID),
			MerchantId:    int32(input.MerchantID),
			PaymentMethod: input.PaymentMethod,
			Amount:        int32(input.Amount),
			UserId:        int32(uid),
		}

		res, err := r.TransactionGraphql.TransactionCommandClient.Create(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "CreateTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransaction(res)

		r.TransactionGraphql.Cache.DeleteTransactionCache(ctx, int(so.Data.ID))

		return so, nil
	})
}

// UpdateTransaction is the resolver for the updateTransaction field.
func (r *mutationResolver) UpdateTransaction(ctx context.Context, input model.UpdateTransactionRequest) (*model.APIResponseTransaction, error) {
	return ResolverHandle(r.ResolverHandle, "UpdateTransaction", ctx, func(ctx context.Context) (*model.APIResponseTransaction, error) {
		id := int32(input.TransactionID)
		if id <= 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: transaction ID cannot be zero"))
		}

		req := &pb_transaction.UpdateTransactionRequest{
			TransactionId: id,
			OrderId:       int32(input.OrderID),
			MerchantId:    int32(input.MerchantID),
			PaymentMethod: input.PaymentMethod,
			Amount:        int32(input.Amount),
		}

		res, err := r.TransactionGraphql.TransactionCommandClient.Update(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "UpdateTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransaction(res)

		r.TransactionGraphql.Cache.DeleteTransactionCache(ctx, int(id))

		return so, nil
	})
}

// TrashedTransaction is the resolver for the trashedTransaction field.
func (r *mutationResolver) TrashedTransaction(ctx context.Context, input model.FindByIDTransactionRequest) (*model.APIResponseTransactionDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "TrashedTransaction", ctx, func(ctx context.Context) (*model.APIResponseTransactionDeleteAt, error) {
		id := int32(input.ID)
		if id <= 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: transaction ID cannot be zero"))
		}

		res, err := r.TransactionGraphql.TransactionCommandClient.TrashedTransaction(ctx, &pb_transaction.FindByIdTransactionRequest{
			Id: id,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "TrashedTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionDeleteAt(res)

		r.TransactionGraphql.Cache.DeleteTransactionCache(ctx, int(id))

		return so, nil
	})
}

// RestoreTransaction is the resolver for the restoreTransaction field.
func (r *mutationResolver) RestoreTransaction(ctx context.Context, input model.FindByIDTransactionRequest) (*model.APIResponseTransactionDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreTransaction", ctx, func(ctx context.Context) (*model.APIResponseTransactionDeleteAt, error) {
		id := int32(input.ID)
		if id <= 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: transaction ID cannot be zero"))
		}

		res, err := r.TransactionGraphql.TransactionCommandClient.RestoreTransaction(ctx, &pb_transaction.FindByIdTransactionRequest{
			Id: id,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionDeleteAt(res)

		r.TransactionGraphql.Cache.DeleteTransactionCache(ctx, int(id))

		return so, nil
	})
}

// DeleteTransactionPermanent is the resolver for the deleteTransactionPermanent field.
func (r *mutationResolver) DeleteTransactionPermanent(ctx context.Context, input model.FindByIDTransactionRequest) (*model.APIResponseTransactionDelete, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteTransactionPermanent", ctx, func(ctx context.Context) (*model.APIResponseTransactionDelete, error) {
		id := int32(input.ID)
		if id <= 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: transaction ID cannot be zero"))
		}

		res, err := r.TransactionGraphql.TransactionCommandClient.DeleteTransactionPermanent(ctx, &pb_transaction.FindByIdTransactionRequest{
			Id: id,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteTransactionPermanent")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionDelete(res)

		r.TransactionGraphql.Cache.DeleteTransactionCache(ctx, int(id))

		return so, nil
	})
}

// RestoreAllTransaction is the resolver for the restoreAllTransaction field.
func (r *mutationResolver) RestoreAllTransaction(ctx context.Context) (*model.APIResponseTransactionAll, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreAllTransaction", ctx, func(ctx context.Context) (*model.APIResponseTransactionAll, error) {
		res, err := r.TransactionGraphql.TransactionCommandClient.RestoreAllTransaction(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreAllTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionAll(res)

		return so, nil
	})
}

// DeleteAllTransactionPermanent is the resolver for the deleteAllTransactionPermanent field.
func (r *mutationResolver) DeleteAllTransactionPermanent(ctx context.Context) (*model.APIResponseTransactionAll, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteAllTransactionPermanent", ctx, func(ctx context.Context) (*model.APIResponseTransactionAll, error) {
		res, err := r.TransactionGraphql.TransactionCommandClient.DeleteAllTransactionPermanent(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteAllTransactionPermanent")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransactionAll(res)

		return so, nil
	})
}

// FindAllTransaction is the resolver for the findAllTransaction field.
func (r *queryResolver) FindAllTransaction(ctx context.Context, input *model.FindAllTransactionRequest) (*model.APIResponsePaginationTransaction, error) {
	return ResolverHandle(r.ResolverHandle, "FindAllTransaction", ctx, func(ctx context.Context) (*model.APIResponsePaginationTransaction, error) {
		// Prepare Input Defaults
		page := int32(1)
		pageSize := int32(10)
		search := ""
		if input != nil {
			if input.Page != nil {
				page = int32(*input.Page)
			}
			if input.PageSize != nil {
				pageSize = int32(*input.PageSize)
			}
			if input.Search != nil {
				search = *input.Search
			}
		}
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		if data, found := r.TransactionGraphql.Cache.GetCachedTransactionsCache(ctx, input); found {
			return data, nil
		}

		pbReq := &pb_transaction.FindAllTransactionRequest{
			Page:     page,
			PageSize: pageSize,
			Search:   search,
		}

		transactions, err := r.TransactionGraphql.TransactionQueryClient.FindAllTransactions(ctx, pbReq)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindAllTransaction")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponsePaginationTransaction(transactions)

		r.TransactionGraphql.Cache.SetCachedTransactionsCache(ctx, input, so)

		return so, nil
	})
}

// FindTransactionByMerchant is the resolver for the findTransactionByMerchant field.
func (r *queryResolver) FindTransactionByMerchant(ctx context.Context, input *model.FindAllTransactionMerchantRequest) (*model.APIResponsePaginationTransaction, error) {
	return ResolverHandle(r.ResolverHandle, "FindTransactionByMerchant", ctx, func(ctx context.Context) (*model.APIResponsePaginationTransaction, error) {
		if input == nil {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: input cannot be nil"))
		}

		page := int32(1)
		pageSize := int32(10)
		merchantID := int32(0)
		search := ""

		if input.Page != nil {
			page = int32(*input.Page)
		}
		if input.PageSize != nil {
			pageSize = int32(*input.PageSize)
		}
		if input.MerchantID != nil {
			merchantID = int32(*input.MerchantID)
		}
		if input.Search != nil {
			search = *input.Search
		}

		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}
		if merchantID <= 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: merchant ID cannot be zero"))
		}

		if data, found := r.TransactionGraphql.Cache.GetCachedTransactionByMerchant(ctx, input); found {
			return data, nil
		}

		req := &pb_transaction.FindAllTransactionByMerchantRequest{
			Page:       page,
			PageSize:   pageSize,
			Search:     search,
			MerchantId: merchantID,
		}

		transactions, err := r.TransactionGraphql.TransactionQueryClient.FindByMerchant(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindTransactionByMerchant")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponsePaginationTransaction(transactions)

		r.TransactionGraphql.Cache.SetCachedTransactionByMerchant(ctx, input, so)

		return so, nil
	})
}

// FindTransactionByID is the resolver for the findTransactionById field.
func (r *queryResolver) FindTransactionByID(ctx context.Context, input model.FindByIDTransactionRequest) (*model.APIResponseTransaction, error) {
	return ResolverHandle(r.ResolverHandle, "FindTransactionByID", ctx, func(ctx context.Context) (*model.APIResponseTransaction, error) {
		id := int(input.ID)
		if id <= 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: transaction ID cannot be zero"))
		}

		if data, found := r.TransactionGraphql.Cache.GetCachedTransactionCache(ctx, id); found {
			return data, nil
		}

		transaction, err := r.TransactionGraphql.TransactionQueryClient.FindById(ctx, &pb_transaction.FindByIdTransactionRequest{
			Id: int32(id),
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindTransactionByID")
		}

		so := r.TransactionGraphql.Mapping.ToGraphqlResponseTransaction(transaction)

		r.TransactionGraphql.Cache.SetCachedTransactionCache(ctx, so)

		return so, nil
	})
}

// FindByActive is the resolver for the findByActive field.
func (r *queryResolver) FindByActive(ctx context.Context, input *model.FindAllTransactionRequest) (*model.APIResponsePaginationTransaction, error) {
	page := int32(1)
	pageSize := int32(10)
	search := ""
	if input != nil {
		if input.Page != nil {
			page = int32(*input.Page)
		}
		if input.PageSize != nil {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}
	}
	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	if data, found := r.TransactionGraphql.Cache.GetCachedTransactionActiveCache(ctx, input); found {
		return data, nil
	}

	req := &pb_transaction.FindAllTransactionRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   search,
	}

	transactions, err := r.TransactionGraphql.TransactionQueryClient.FindByActive(ctx, req)
	if err != nil {
		return nil, r.handleGraphQLError(err, "FindByActive")
	}

	res := r.TransactionGraphql.Mapping.ToGraphqlResponsePaginationTransaction(transactions)
	r.TransactionGraphql.Cache.SetCachedTransactionActiveCache(ctx, input, res)
	return res, nil
}

// FindByTrashed is the resolver for the findByTrashed field.
func (r *queryResolver) FindByTrashed(ctx context.Context, input *model.FindAllTransactionRequest) (*model.APIResponsePaginationTransactionDeleteAt, error) {
	page := int32(1)
	pageSize := int32(10)
	search := ""
	if input != nil {
		if input.Page != nil {
			page = int32(*input.Page)
		}
		if input.PageSize != nil {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}
	}
	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	if data, found := r.TransactionGraphql.Cache.GetCachedTransactionTrashedCache(ctx, input); found {
		return data, nil
	}

	req := &pb_transaction.FindAllTransactionRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   search,
	}

	transactions, err := r.TransactionGraphql.TransactionQueryClient.FindByTrashed(ctx, req)
	if err != nil {
		return nil, r.handleGraphQLError(err, "FindByTrashed")
	}

	res := r.TransactionGraphql.Mapping.ToGraphqlResponsePaginationTransactionDeleteAt(transactions)
	r.TransactionGraphql.Cache.SetCachedTransactionTrashedCache(ctx, input, res)
	return res, nil
}
