package transactiongraphqlmapper

import (
	"github.com/MamangRust/microservice-ecommerce-grpc-apigateway/internal/model"
	"github.com/MamangRust/microservice-ecommerce-grpc-pb/transaction"
)

type TransactionGraphqlMapper interface {
	ToGraphqlResponseTransaction(res *pb_transaction.ApiResponseTransaction) *model.APIResponseTransaction
	ToGraphqlResponseTransactionDeleteAt(res *pb_transaction.ApiResponseTransactionDeleteAt) *model.APIResponseTransactionDeleteAt
	ToGraphqlResponseTransactionDelete(res *pb_transaction.ApiResponseTransactionDelete) *model.APIResponseTransactionDelete
	ToGraphqlResponseTransactionAll(res *pb_transaction.ApiResponseTransactionAll) *model.APIResponseTransactionAll
	ToGraphqlResponsePaginationTransactionDeleteAt(res *pb_transaction.ApiResponsePaginationTransactionDeleteAt) *model.APIResponsePaginationTransactionDeleteAt
	ToGraphqlResponsePaginationTransaction(res *pb_transaction.ApiResponsePaginationTransaction) *model.APIResponsePaginationTransaction
	ToGraphqlResponseMonthAmountSuccess(res *pb_transaction.ApiResponseTransactionMonthAmountSuccess) *model.APIResponseTransactionMonthAmountSuccess
	ToGraphqlResponseYearAmountSuccess(res *pb_transaction.ApiResponseTransactionYearAmountSuccess) *model.APIResponseTransactionYearAmountSuccess
	ToGraphqlResponseMonthAmountFailed(res *pb_transaction.ApiResponseTransactionMonthAmountFailed) *model.APIResponseTransactionMonthAmountFailed
	ToGraphqlResponseYearAmountFailed(res *pb_transaction.ApiResponseTransactionYearAmountFailed) *model.APIResponseTransactionYearAmountFailed
	ToGraphqlResponseMonthMethod(res *pb_transaction.ApiResponseTransactionMonthPaymentMethod) *model.APIResponseTransactionMonthPaymentMethod
	ToGraphqlResponseYearMethod(res *pb_transaction.ApiResponseTransactionYearPaymentmethod) *model.APIResponseTransactionYearPaymentMethod
}
