package merchant

import sharedpb "github.com/MamangRust/microservice-ecommerce-shared/pb"

type merchantAwardCommandServiceClient = sharedpb.merchantAwardCommandServiceClient
type merchantAwardQueryServiceClient = sharedpb.merchantAwardQueryServiceClient
type merchantBusinessCommandServiceClient = sharedpb.merchantBusinessCommandServiceClient
type merchantBusinessQueryServiceClient = sharedpb.merchantBusinessQueryServiceClient
type merchantCommandServiceClient = sharedpb.merchantCommandServiceClient
type merchantDetailCommandServiceClient = sharedpb.merchantDetailCommandServiceClient
type merchantDetailQueryServiceClient = sharedpb.merchantDetailQueryServiceClient
type merchantDocumentCommandServiceClient = sharedpb.merchantDocumentCommandServiceClient
type merchantDocumentQueryServiceClient = sharedpb.merchantDocumentQueryServiceClient
type merchantPolicyCommandServiceClient = sharedpb.merchantPolicyCommandServiceClient
type merchantPolicyQueryServiceClient = sharedpb.merchantPolicyQueryServiceClient
type merchantQueryServiceClient = sharedpb.merchantQueryServiceClient
type merchantSocialCommandServiceClient = sharedpb.merchantSocialCommandServiceClient
var NewCategoryStatsByMerchantServiceClient = sharedpb.NewCategoryStatsByMerchantServiceClient
var NewMerchantAwardCommandServiceClient = sharedpb.NewMerchantAwardCommandServiceClient
var NewMerchantAwardQueryServiceClient = sharedpb.NewMerchantAwardQueryServiceClient
var NewMerchantBusinessCommandServiceClient = sharedpb.NewMerchantBusinessCommandServiceClient
var NewMerchantBusinessQueryServiceClient = sharedpb.NewMerchantBusinessQueryServiceClient
var NewMerchantCommandServiceClient = sharedpb.NewMerchantCommandServiceClient
var NewMerchantDetailCommandServiceClient = sharedpb.NewMerchantDetailCommandServiceClient
var NewMerchantDetailQueryServiceClient = sharedpb.NewMerchantDetailQueryServiceClient
var NewMerchantDocumentCommandServiceClient = sharedpb.NewMerchantDocumentCommandServiceClient
var NewMerchantDocumentQueryServiceClient = sharedpb.NewMerchantDocumentQueryServiceClient
var NewMerchantPolicyCommandServiceClient = sharedpb.NewMerchantPolicyCommandServiceClient
var NewMerchantPolicyQueryServiceClient = sharedpb.NewMerchantPolicyQueryServiceClient
var NewMerchantQueryServiceClient = sharedpb.NewMerchantQueryServiceClient
var NewMerchantSocialCommandServiceClient = sharedpb.NewMerchantSocialCommandServiceClient
var NewTransactionStatsByMerchantServiceClient = sharedpb.NewTransactionStatsByMerchantServiceClient
var RegisterCategoryStatsByMerchantServiceServer = sharedpb.RegisterCategoryStatsByMerchantServiceServer
var RegisterMerchantAwardCommandServiceServer = sharedpb.RegisterMerchantAwardCommandServiceServer
var RegisterMerchantAwardQueryServiceServer = sharedpb.RegisterMerchantAwardQueryServiceServer
var RegisterMerchantBusinessCommandServiceServer = sharedpb.RegisterMerchantBusinessCommandServiceServer
var RegisterMerchantBusinessQueryServiceServer = sharedpb.RegisterMerchantBusinessQueryServiceServer
var RegisterMerchantCommandServiceServer = sharedpb.RegisterMerchantCommandServiceServer
var RegisterMerchantDetailCommandServiceServer = sharedpb.RegisterMerchantDetailCommandServiceServer
var RegisterMerchantDetailQueryServiceServer = sharedpb.RegisterMerchantDetailQueryServiceServer
var RegisterMerchantDocumentCommandServiceServer = sharedpb.RegisterMerchantDocumentCommandServiceServer
var RegisterMerchantDocumentQueryServiceServer = sharedpb.RegisterMerchantDocumentQueryServiceServer
var RegisterMerchantPolicyCommandServiceServer = sharedpb.RegisterMerchantPolicyCommandServiceServer
var RegisterMerchantPolicyQueryServiceServer = sharedpb.RegisterMerchantPolicyQueryServiceServer
var RegisterMerchantQueryServiceServer = sharedpb.RegisterMerchantQueryServiceServer
var RegisterMerchantSocialCommandServiceServer = sharedpb.RegisterMerchantSocialCommandServiceServer
var RegisterTransactionStatsByMerchantServiceServer = sharedpb.RegisterTransactionStatsByMerchantServiceServer
